### ISSUE TITLE
Switch to final PSR-11 package

### ISSUE THREAD

**Issue by mindplay-dk** [mindplay-dk/unbox#11]
Switch to the official, final PSR-11 package, `psr/container^1`.

Should this be in `2.0.1` or `3.0.0`?

Due to the namespace change, this could be considered a breaking change, or not - if a package (correctly) depends on `container-interop/container-interop^1` now, to install this release of unbox, it will need to adapt to the breaking change in that package first, so this could be considered a minor.

On the other hand, if someone didn't explicitly include this requirement, and inherited the dependency on `container-interop/container-interop` from unbox, this change would break their code.

Perhaps this should be deferred to `3.0.0`, but in that case, we should consider any other breaking changes we might want in this release - in particular:

 * the `ProviderInterface` method-name currently is `register` - this currently blocks `ContainerFactory` from implementing that interface, which might be alternative to the `import()` method proposed in #9.

 * the use of `Interface` suffixes. (though we inherit this artifact from `ContainerInterface` and other PSR packages in our daily environment, so the counter-argument here would be consistency. ugh.)

**Comment by mindplay-dk** [comment]
Hm, it turns out, supporting both interfaces as the same time is only possible by *not* upgrading to the official package - because they decided to update the old package and make it's interfaces extend the official ones, and PHP won't let you implement the same interface twice.

In other words, we can either do nothing and implement the official final interfaces implicitly by inheriting them - or completely break backwards compatibility and remove support for the old interfaces.

While I strongly dislike the fact that we can't give any indication that this package works with the official, final interfaces, breaking backwards compatibility at this time is not desirable, so I will slate this change for the next major milestone, e.g. `3.0.0`, which may or may not ever happen.

I wish the PSR-11 team hadn't made it impossible to transition by deprecating supporting for the old interfaces, but unfortunately that's not possible.

**Comment by simondeeley** [comment]
I was about to make a comment regarding this, suggesting that those people who implicitly rely on other packages for dependencies without explicitly declaring them in their own packages would be an edge-case, I suggest.

However, your above observation over container-interop extending PSR-11 does kinda make that point moot 🤐

**Comment by mindplay-dk** [comment]
Well, it's going on a year.

Hopefully, by now, most people have upgraded to the final version of PSR-11.

The old package has been flagged as deprecated, so if someone declared the dependency on it, they will get a warning at install - and if they didn't, well, they will have to experience this failure when they upgrade, forcing them to fix the issue.

I'm going to switch to the final package and publish this as a minor release.
